# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    app.redis_host: '%env(REDIS_HOST)%'
    app.redis_port: '%env(int:REDIS_PORT)%'
    app.redis_password: '%env(REDIS_PASSWORD)%'
    app.redis_database: 1
    app.redis_dsn: '%env(resolve:REDIS_URL)%'
    app.admin_email: '%env(ADMIN_EMAIL)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\Redis\RedisService:
        arguments:
            $redisHost: '%app.redis_host%'
            $redisPort: '%app.redis_port%'
            $redisPassword: '%app.redis_password%'
            $redisDatabase: '%app.redis_database%'

    App\Service\VerificationCode\VerificationCodeGeneratorInterface: '@App\Service\VerificationCode\DigitVerificationCodeGenerator'


    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones


when@test:
    services:
        _defaults:
            public: true
        App\Service\Redis\RedisService:
            arguments:
                $redisHost: '%app.redis_host%'
                $redisPort: '%app.redis_port%'
                $redisPassword: '%app.redis_password%'
                $redisDatabase: 2
        App\Service\VerificationCode\VerificationCodeGeneratorInterface: '@App\Service\VerificationCode\StaticVerificationCodeGenerator'
